### ISSUE TITLE
Cycle 4: Track down the Cycle 3 checklist.

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-finance#11]
Find the checklist.

**Comment by kelle** [comment]
I dug around and couldn't find a checklist. So I guess that means we need to make one.

**Comment by jdswinbank** [comment]
Just to be clear — which checklist? Or rather: a checklist for what? Finance Committee actions? Things that need to go in proposals? Something else?

**Comment by kelle** [comment]
There wasn't one. We've created a new planning document: https://docs.google.com/document/d/1DXk9qrOqGH7JFWHQdNjZcSpfQuu5uUR5FSKMjypVBxc/edit
