### ISSUE TITLE
Moore spend down?

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-finance#14]
At this point, I think it will be very difficult for us to spend down the Moore budget from Apr 30, 2024.  Do others agree?  

If yes, what should we do? I would assume reaching out to them sooner rather than later is the answer.

**Comment by hamogu** [comment]
How much money is left? The RSE's are currently expecting and end in March 2024. We can ask if they are interested to extend till April 2024.

**Comment by jdswinbank** [comment]
> Do others agree?

...no. 😀

The Finance Committee discussed this on Slack. As of now, the outstanding Moore budget is effectively all spoken for. We are confirming with the designated recipients that they really will be able to invoice on the relevant timescale. Assuming they don't foresee any problems, we should be on track. I'm therefore going to close this down for now.
