### ISSUE TITLE
Provide 2023 receipts for Read the Docs to NumFOCUS

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-finance#3]
We need to dig up the Reciepts for read the docs since Jan 2023.

**Comment by kelle** [comment]
I have asked Ana to do this but am not sure of the status

**Comment by jdswinbank** [comment]
To be explicit, these receipts need to be shared with Mir Mueller, [per mail of 14 November](https://groups.google.com/g/astropy-finance-committee/c/5ahX5ps-MYI/m/q2WRZyIVCwAJ).

**Comment by AnaGabela** [comment]
I will take a look this afternoon if it needs more time they will be first thing to do tomorrow morning!

**Comment by AnaGabela** [comment]
Receipts sent.

**Comment by jdswinbank** [comment]
🎉
