### ISSUE TITLE
Convince NumFocus to allow a per diem

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-finance#6]
Right now, as far as we know, the NumFocus travel policy is to require all meal receipts.  We'd much prefer a per diem style.  This issue needs to be discussed with NumFocus. 

Also related to us establishing a more proper travel reimbursement policy. #5

**Comment by aaryapatil** [comment]
I discussed this with NumFocus. Unfortunately, grant and federal requirements are that receipts should be collected by NumFocus. So, per diem is not possible at the moment.

**Comment by jdswinbank** [comment]
Pretty sure this isn't actually an answer — I regularly receive a per diem while travelling on NSF grants, and of course Moore etc have their own requirements.

It may be that this simply isn't worth arguing with NumFOCUS about, but I don't love their answer.
